set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(LLVM_MINGW $ENV{LLVM_MINGW})
set(TARGET_TRIPLE x86_64-w64-mingw32)

set(CMAKE_C_COMPILER ${LLVM_MINGW}/bin/${TARGET_TRIPLE}-clang)
set(CMAKE_CXX_COMPILER ${LLVM_MINGW}/bin/${TARGET_TRIPLE}-clang++)
set(CMAKE_RC_COMPILER ${LLVM_MINGW}/bin/${TARGET_TRIPLE}-windres)
set(CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS ${LLVM_MINGW}/bin/${TARGET_TRIPLE}-clang-scan-deps)

# Append so that Qt target prefix given by the preset is kept
list(APPEND CMAKE_FIND_ROOT_PATH ${LLVM_MINGW}/${TARGET_TRIPLE})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
